const item_data = [
	{
		'id':1,
		'name':'fishing shirt vest',
		'category':'tops',
		'price':20900,
		'text':'vintageのフィッシングベストをイメージソースに仕上げたシャツベストです。マチをとった大きなポケットがポイントで、一枚で様になるデザインです。',
		'brand':'AAA',
		'new':true,
		'material':'表地：　綿　100%  　 ポリエステル　100%',
		'urazimaterial':'',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,3]' ,
	

		
	},
	{
		'id':2,
		'name':'Bid DRESS',
		'category':'tops',
		'price':20900,
		'text':'肉厚のリネンの素材を使用したドレスです。アメリカンスリーブのような首元のデザインがポイントです。',
		'brand':'AAA',
		'new':true,
		'material':'表地：　リネン　100% ',
		'urazimaterial':'裏地：　ポリエステル 65% 　　綿　35%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
    'color':'[2]' ,
	
	},
	{
		'id':3,
		'name':'HULA CRAFT SKIRT',
		'category':'bottom',
		'price':20900,
		'text':'人と自然に大切に育てられたオーガニックコットンを100%使用した生地にワッシャー加工を施しヴィンテージライクな凸凹のシワとリラックスしたクラフト感のある生地を使用したスカートです。',
		'brand':'BBB',
		'new':true,
		'material':'表地：　綿　100%  ',
		'urazimaterial':'裏地：　綿  100%    ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[2]' ,
		
	},
	{
		'id':4,
		'name':'HURA PLAID SKIRT',
		'category':'bottom',
		'price':20900,
		'text':'人と自然に大切に育てられたオーガニックコットンを100%使用した生地にワッシャー加工を施しヴィンテージライクな凸凹のシワとリラックスしたクラフト感のある生地を使用したスカートです。',
		'brand':'BBB',
		'new':true,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1]' ,
		
  },
	{
		'id':5,
		'name':'Bagel cuff',
		'category':'accessory',
		'price':9900,
		'text':'籐（ラタン）素材のbagelのような型のバングルになります。籐は天然素材で、工業化が進んだ現在でも全て一つ一つ手作りで熟練の職人が作っています',
		'brand':'DDD',
		'new':true,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':6,
		'name':'Umii tank',
		'category':'tops',
		'price':5500,
		'text':'生地はヴィンテージの生地を再現して作られた少し肉厚の肌触りの良い国産のリサイクルコットンを選びました。伸縮性が良く下着のラインも出にくいので一枚でも可愛く着て頂けます。',
		'brand':'AAA',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[5,6,7]' ,
  },
	{
		'id':7,
		'name':'Umii T',
		'category':'tops',
		'price':6600,
		'text':'生地はヴィンテージの生地を再現して作られた少し肉厚の肌触りの良い国産のリサイクルコットンを選びました。伸縮性が良く下着のラインも出にくいので一枚でも可愛く着て頂けます。',
		'brand':'DDD',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[5,6,7]' ,
  },
	{
		'id':8,
		'name':'Umii sleeve',
		'category':'tops',
		'price':9900,
		'text':'生地はヴィンテージの生地を再現して作られた少し肉厚の肌触りの良い国産のリサイクルコットンを選びました。伸縮性が良く下着のラインも出にくいので一枚でも可愛く着て頂けます。',
		'brand':'EEE',
		'new':true,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[5,6,7]' ,
  },
	{
		'id':9,
		'name':'TENT SMOCK',
		'category':'tops',
		'price':16500,
		'text':'1930年代のフレンチヴィンテージのチャーチスモックをベースに仕上げたチュニックシャツです。バイオ加工をかけた綿100%の生地は皺を気にせず着て頂けます。',
		'brand':'EEE',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[4,2]' ,
  },
	{
		'id':10,
		'name':'See line DRESS',
		'category':'tops',
		'price':18700,
		'text':'"See（会う）LINE DRESS" は何かと合わせることをベースにして考えたシャツワンピースです。着て頂く方のアイデアで何通りもの着こなしをお楽しみ頂けるワンピースです。',
		'brand':'EEE',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[4]' ,
  },
	{
		'id':11,
		'name':'SHEEP SHIRT',
		'category':'tops',
		'price':14300,
		'text':'ボリュームスリーブがポイントのシャツブラウス。ランダムに入れたタックがお袖の膨らみを出してくれます。',
		'brand':'DDD',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,
  },
	{
		'id':12,
		'name':'See DRESS',
		'category':'tops',
		'price':18700,
		'text':'生地はヴィンテージの生地を再現して作られた少し肉厚の肌触りの良い国産のリサイクルコットンを選びました。伸縮性が良く下着のラインも出にくいので一枚でも可愛く着て頂けます。',
		'brand':'BBB',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,
  },
	{
		'id':13,
		'name':'SNOW OVERALLS',
		'category':'bottom',
		'price':20900,
		'text':'綿100%の生地にバイオ加工を施しヴィンテージライクな見え方の生地を使用したビッグサイズなオーバーオール。立体感が出るようにオーバーオールには珍しいタックを2本入れているので、サラッと着るだけで様になるシルエットをお楽しみ頂けます。',
		'brand':'CCC',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,
  },
	{
		'id':14,
		'name':'oddly trouser',
		'category':'bottom',
		'price':17600,
		'text':'綿100%の生地にバイオ加工を施しヴィンテージライクな見え方の生地を使用したパンツです。シームポケットに加えサイドに配したビックサイズのポケットやウエストに沢山入ったタックのデザインがポイントになるのでトップスをインしても◎',
		'brand':'CCC',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,
  },
	{
		'id':15,
		'name':'ANCHOR SHACKLE O RING',
		'category':'accessory',
		'price':8800,
		'text':'ネックレストップとして、バングルとして、キーホルダーとして、色々な使い方でお楽しみ頂けます。主に船などで使われる金具をアクセサリーとして再構築し作成しました。',
		'brand':'CCC',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,
  },
	{
		'id':16,
		'name':'B ring',
		'category':'accessory',
		'price':7700,
		'text':'B ringのBはblass（真鍮）はもちろんですが、bliss（恵み・祝福）とゆう大好きな言葉の頭文字をとりました。歓びに包まれ、素晴らしい出来事に恵まれますようにと願いをこめてつくりました。',
		'brand':'EEE',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':17,
		'name':'PAPA TOTE',
		'category':'accessory',
		'price':8800,
		'text':'創業130年の歴史を誇る老舗の工場TAKEYARIの帆布を使用したトートバッグ。最初は硬い帆布ですが使い込むことによって柔らかく風合いが増していき、時間とともに変化する味わいが魅力で愛着の増す生地を選びました。',
		'brand':'BBB',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':18,
		'name':'Maki hat',
		'category':'accessory',
		'price':"8800",
		'text':'天然感をキープしながらシワになりにくく接触冷感のある国内のハイパワーストレッチ素材を使用しています。被って巻くだけなので、不器用な私でも簡単にオシャレにターバンスタイルが出来るデザインです。',
		'brand':'BBB',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':19,
		'name':'FAB BAG',
		'category':'accessory',
		'price':13800,
		'text':'ウールの産地尾州で太番手の糸をさらに3本撚り合わせ織られた生地を使用しています。ヴィンテージのメキシカンパーカーの生地の規格をベースに作られた生地は使い込むうちに肌に馴染んできます。',
		'brand':'BBB',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':20,
		'name':'POCKET WIND APRON',
		'category':'accessory',
		'price':12100,
		'text':'綿100%の少し目が荒めの生地を使用したエプロンワンピース。',
		'brand':'AAA',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿　100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':21,
		'name':'Bib vest',
		'category':'tops',
		'price':9900,
		'text':'ウールの産地尾州で太番手の糸をさらに3本撚り合わせ織られた生地を使用しています。ヴィンテージのメキシカンパーカーの生地の規格をベースに作られた生地は使い込むうちに肌に馴染んできます。首の部分を外して垂らし、ウエストベルトのような使い方もおススメです。',
		'brand':'CCC',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },
	{
		'id':22,
		'name':'POCKET WIND APRON',
		'category':'bottom',
		'price':12100,
		'text':'綿100%の少し目が荒めの生地を使用したエプロンワンピース。シンプルに腰に巻いて頂いたり、ワンショルダー風に巻いてもらったり、キャミワンピースのような着方が出来たりと自由に着て頂けるアイテム。',
		'brand':'AAA',
		'new':false,
		'material':'表地　綿　100%   ポリエステル　100%',
		'urazimaterial':'裏地　綿 100%   ポリエステル　100%',
		'spec':'着丈：129cm  裾幅：105cm',
		'speclist':'バスト：84cm　ウエスト：77cm ヒップ：98cm',
		'color':'[1,2]' ,

  },

	
	
]
